[programs.devnet]
myepicproject = "4KCfsDf6inyHaGCuvdNEYYCPGrh7cxqMwqTRivAiShX6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/maxwelltsao/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
